//! Shared authoritative component declarations for typed world storage.

macro_rules! with_authoritative_components {
    ($callback:ident) => {
        $callback! {
            {
                names,
                Name,
                insert_name,
                get_name,
                get_name_mut,
                remove_name,
                has_name,
                iter_names,
                insert_component_name,
                get_component_name,
                get_component_name_mut,
                remove_component_name,
                has_component_name,
                entities_with_name,
                query_name,
                count_with_name,
                "Name",
                |_| true,
                Name
            }
            {
                agents,
                AgentData,
                insert_agent_data,
                get_agent_data,
                get_agent_data_mut,
                remove_agent_data,
                has_agent_data,
                iter_agent_data,
                insert_component_agent_data,
                get_component_agent_data,
                get_component_agent_data_mut,
                remove_component_agent_data,
                has_component_agent_data,
                entities_with_agent_data,
                query_agent_data,
                count_with_agent_data,
                "AgentData",
                |kind| kind == EntityKind::Agent,
                AgentData
            }
            {
                wound_lists,
                WoundList,
                insert_wound_list,
                get_wound_list,
                get_wound_list_mut,
                remove_wound_list,
                has_wound_list,
                iter_wound_lists,
                insert_component_wound_list,
                get_component_wound_list,
                get_component_wound_list_mut,
                remove_component_wound_list,
                has_component_wound_list,
                entities_with_wound_list,
                query_wound_list,
                count_with_wound_list,
                "WoundList",
                |kind| kind == EntityKind::Agent,
                WoundList
            }
            {
                drive_thresholds,
                DriveThresholds,
                insert_drive_thresholds,
                get_drive_thresholds,
                get_drive_thresholds_mut,
                remove_drive_thresholds,
                has_drive_thresholds,
                iter_drive_thresholds,
                insert_component_drive_thresholds,
                get_component_drive_thresholds,
                get_component_drive_thresholds_mut,
                remove_component_drive_thresholds,
                has_component_drive_thresholds,
                entities_with_drive_thresholds,
                query_drive_thresholds,
                count_with_drive_thresholds,
                "DriveThresholds",
                |kind| kind == EntityKind::Agent,
                DriveThresholds
            }
            {
                homeostatic_needs,
                HomeostaticNeeds,
                insert_homeostatic_needs,
                get_homeostatic_needs,
                get_homeostatic_needs_mut,
                remove_homeostatic_needs,
                has_homeostatic_needs,
                iter_homeostatic_needs,
                insert_component_homeostatic_needs,
                get_component_homeostatic_needs,
                get_component_homeostatic_needs_mut,
                remove_component_homeostatic_needs,
                has_component_homeostatic_needs,
                entities_with_homeostatic_needs,
                query_homeostatic_needs,
                count_with_homeostatic_needs,
                "HomeostaticNeeds",
                |kind| kind == EntityKind::Agent,
                HomeostaticNeeds
            }
            {
                deprivation_exposures,
                DeprivationExposure,
                insert_deprivation_exposure,
                get_deprivation_exposure,
                get_deprivation_exposure_mut,
                remove_deprivation_exposure,
                has_deprivation_exposure,
                iter_deprivation_exposures,
                insert_component_deprivation_exposure,
                get_component_deprivation_exposure,
                get_component_deprivation_exposure_mut,
                remove_component_deprivation_exposure,
                has_component_deprivation_exposure,
                entities_with_deprivation_exposure,
                query_deprivation_exposure,
                count_with_deprivation_exposure,
                "DeprivationExposure",
                |kind| kind == EntityKind::Agent,
                DeprivationExposure
            }
            {
                metabolism_profiles,
                MetabolismProfile,
                insert_metabolism_profile,
                get_metabolism_profile,
                get_metabolism_profile_mut,
                remove_metabolism_profile,
                has_metabolism_profile,
                iter_metabolism_profiles,
                insert_component_metabolism_profile,
                get_component_metabolism_profile,
                get_component_metabolism_profile_mut,
                remove_component_metabolism_profile,
                has_component_metabolism_profile,
                entities_with_metabolism_profile,
                query_metabolism_profile,
                count_with_metabolism_profile,
                "MetabolismProfile",
                |kind| kind == EntityKind::Agent,
                MetabolismProfile
            }
            {
                carry_capacities,
                CarryCapacity,
                insert_carry_capacity,
                get_carry_capacity,
                get_carry_capacity_mut,
                remove_carry_capacity,
                has_carry_capacity,
                iter_carry_capacities,
                insert_component_carry_capacity,
                get_component_carry_capacity,
                get_component_carry_capacity_mut,
                remove_component_carry_capacity,
                has_component_carry_capacity,
                entities_with_carry_capacity,
                query_carry_capacity,
                count_with_carry_capacity,
                "CarryCapacity",
                |kind| kind == EntityKind::Agent,
                CarryCapacity
            }
            {
                resource_sources,
                ResourceSource,
                insert_resource_source,
                get_resource_source,
                get_resource_source_mut,
                remove_resource_source,
                has_resource_source,
                iter_resource_sources,
                insert_component_resource_source,
                get_component_resource_source,
                get_component_resource_source_mut,
                remove_component_resource_source,
                has_component_resource_source,
                entities_with_resource_source,
                query_resource_source,
                count_with_resource_source,
                "ResourceSource",
                |kind| kind == EntityKind::Facility || kind == EntityKind::Place,
                ResourceSource
            }
            {
                in_transit_on_edges,
                InTransitOnEdge,
                insert_in_transit_on_edge,
                get_in_transit_on_edge,
                get_in_transit_on_edge_mut,
                remove_in_transit_on_edge,
                has_in_transit_on_edge,
                iter_in_transit_on_edges,
                insert_component_in_transit_on_edge,
                get_component_in_transit_on_edge,
                get_component_in_transit_on_edge_mut,
                remove_component_in_transit_on_edge,
                has_component_in_transit_on_edge,
                entities_with_in_transit_on_edge,
                query_in_transit_on_edge,
                count_with_in_transit_on_edge,
                "InTransitOnEdge",
                |kind| kind == EntityKind::Agent,
                InTransitOnEdge
            }
            {
                item_lots,
                ItemLot,
                insert_item_lot,
                get_item_lot,
                get_item_lot_mut,
                remove_item_lot,
                has_item_lot,
                iter_item_lots,
                insert_component_item_lot,
                get_component_item_lot,
                get_component_item_lot_mut,
                remove_component_item_lot,
                has_component_item_lot,
                entities_with_item_lot,
                query_item_lot,
                count_with_item_lot,
                "ItemLot",
                |kind| kind == EntityKind::ItemLot,
                ItemLot
            }
            {
                unique_items,
                UniqueItem,
                insert_unique_item,
                get_unique_item,
                get_unique_item_mut,
                remove_unique_item,
                has_unique_item,
                iter_unique_items,
                insert_component_unique_item,
                get_component_unique_item,
                get_component_unique_item_mut,
                remove_component_unique_item,
                has_component_unique_item,
                entities_with_unique_item,
                query_unique_item,
                count_with_unique_item,
                "UniqueItem",
                |kind| kind == EntityKind::UniqueItem,
                UniqueItem
            }
            {
                containers,
                Container,
                insert_container,
                get_container,
                get_container_mut,
                remove_container,
                has_container,
                iter_containers,
                insert_component_container,
                get_component_container,
                get_component_container_mut,
                remove_component_container,
                has_component_container,
                entities_with_container,
                query_container,
                count_with_container,
                "Container",
                |kind| kind == EntityKind::Container,
                Container
            }
        }
    };
}

pub(crate) use with_authoritative_components;

macro_rules! with_txn_simple_set_components {
    ($callback:ident) => {
        $callback! {
            {
                crate::Name,
                get_component_name,
                remove_component_name,
                insert_component_name,
                set_component_name,
                clear_component_name,
                Name
            }
            {
                crate::AgentData,
                get_component_agent_data,
                remove_component_agent_data,
                insert_component_agent_data,
                set_component_agent_data,
                clear_component_agent_data,
                AgentData
            }
            {
                crate::WoundList,
                get_component_wound_list,
                remove_component_wound_list,
                insert_component_wound_list,
                set_component_wound_list,
                clear_component_wound_list,
                WoundList
            }
            {
                crate::DriveThresholds,
                get_component_drive_thresholds,
                remove_component_drive_thresholds,
                insert_component_drive_thresholds,
                set_component_drive_thresholds,
                clear_component_drive_thresholds,
                DriveThresholds
            }
            {
                crate::HomeostaticNeeds,
                get_component_homeostatic_needs,
                remove_component_homeostatic_needs,
                insert_component_homeostatic_needs,
                set_component_homeostatic_needs,
                clear_component_homeostatic_needs,
                HomeostaticNeeds
            }
            {
                crate::DeprivationExposure,
                get_component_deprivation_exposure,
                remove_component_deprivation_exposure,
                insert_component_deprivation_exposure,
                set_component_deprivation_exposure,
                clear_component_deprivation_exposure,
                DeprivationExposure
            }
            {
                crate::MetabolismProfile,
                get_component_metabolism_profile,
                remove_component_metabolism_profile,
                insert_component_metabolism_profile,
                set_component_metabolism_profile,
                clear_component_metabolism_profile,
                MetabolismProfile
            }
            {
                crate::CarryCapacity,
                get_component_carry_capacity,
                remove_component_carry_capacity,
                insert_component_carry_capacity,
                set_component_carry_capacity,
                clear_component_carry_capacity,
                CarryCapacity
            }
            {
                crate::ResourceSource,
                get_component_resource_source,
                remove_component_resource_source,
                insert_component_resource_source,
                set_component_resource_source,
                clear_component_resource_source,
                ResourceSource
            }
            {
                crate::InTransitOnEdge,
                get_component_in_transit_on_edge,
                remove_component_in_transit_on_edge,
                insert_component_in_transit_on_edge,
                set_component_in_transit_on_edge,
                clear_component_in_transit_on_edge,
                InTransitOnEdge
            }
        }
    };
}

pub(crate) use with_txn_simple_set_components;
