//! Control source for entities — determines input capture, never simulation legality.

use serde::{Deserialize, Serialize};

/// Determines how an entity receives input.
///
/// There is no `Player` type — `ControlSource::Human` means the entity's
/// decisions come from a human player, but simulation rules treat all
/// control sources identically.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug, Serialize, Deserialize)]
pub enum ControlSource {
    /// Input captured from a human player.
    Human,
    /// Input generated by the AI planner.
    Ai,
    /// No active input source (dormant entity).
    None,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_bounds<
        T: Copy
            + Clone
            + Eq
            + std::hash::Hash
            + std::fmt::Debug
            + Serialize
            + serde::de::DeserializeOwned,
    >() {
    }

    #[test]
    fn control_source_trait_bounds() {
        assert_bounds::<ControlSource>();
    }

    #[test]
    fn control_source_bincode_roundtrip() {
        for variant in [ControlSource::Human, ControlSource::Ai, ControlSource::None] {
            let bytes = bincode::serialize(&variant).unwrap();
            let back: ControlSource = bincode::deserialize(&bytes).unwrap();
            assert_eq!(variant, back);
        }
    }
}
