#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
from collections import OrderedDict
from typing import Iterable

ROOT = pathlib.Path(__file__).resolve().parents[1]
TESTS_DIR = ROOT / "crates" / "worldwake-ai" / "tests"
OUTPUT_PATH = ROOT / "docs" / "generated" / "golden-e2e-inventory.md"
DOCS_TO_VALIDATE = (
    ROOT / "docs" / "golden-e2e-coverage.md",
    ROOT / "docs" / "golden-e2e-scenarios.md",
    ROOT / "docs" / "golden-e2e-testing.md",
)

SOURCE_TEST_RE = re.compile(r"(?m)^fn (golden_[a-z0-9_]+)\s*\(")
DOC_TEST_REF_RE = re.compile(r"`(golden_[a-z0-9_]+)`")
RUNNING_GOLDEN_BINARY_RE = re.compile(r"^\s*Running tests/(golden_[^ ]+\.rs) ")
RUNNING_ANY_BINARY_RE = re.compile(r"^\s*Running ")
LISTED_TEST_RE = re.compile(r"^(golden_[a-z0-9_]+): test$", re.MULTILINE)


def parse_source_inventory(tests_dir: pathlib.Path) -> OrderedDict[str, list[str]]:
    inventory: OrderedDict[str, list[str]] = OrderedDict()
    for path in sorted(tests_dir.glob("golden_*.rs")):
        inventory[path.name] = SOURCE_TEST_RE.findall(path.read_text())
    return inventory


def parse_cargo_test_list_output(output: str) -> OrderedDict[str, list[str]]:
    inventory: OrderedDict[str, list[str]] = OrderedDict()
    current_file: str | None = None
    for raw_line in output.splitlines():
        line = raw_line.rstrip()
        running_match = RUNNING_GOLDEN_BINARY_RE.match(line)
        if running_match:
            current_file = running_match.group(1)
            inventory.setdefault(current_file, [])
            continue
        if RUNNING_ANY_BINARY_RE.match(line):
            current_file = None
            continue
        if current_file is None:
            continue
        listed_match = LISTED_TEST_RE.match(line)
        if listed_match:
            inventory[current_file].append(listed_match.group(1))
    return inventory


def run_cargo_test_list(root: pathlib.Path) -> OrderedDict[str, list[str]]:
    inventory: OrderedDict[str, list[str]] = OrderedDict()
    for path in sorted(TESTS_DIR.glob("golden_*.rs")):
        result = subprocess.run(
            [
                "cargo",
                "test",
                "-p",
                "worldwake-ai",
                "--test",
                path.stem,
                "--",
                "--list",
            ],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        )
        combined = result.stdout + "\n" + result.stderr
        inventory[path.name] = LISTED_TEST_RE.findall(combined)
    return inventory


def flatten_inventory(inventory: OrderedDict[str, list[str]]) -> list[str]:
    return [name for names in inventory.values() for name in names]


def count_files_with_goldens(inventory: OrderedDict[str, list[str]]) -> int:
    return sum(1 for names in inventory.values() if names)


def compare_inventories(
    source_inventory: OrderedDict[str, list[str]],
    cargo_inventory: OrderedDict[str, list[str]],
) -> list[str]:
    errors: list[str] = []
    all_files = sorted(set(source_inventory) | set(cargo_inventory))
    for file_name in all_files:
        source_names = source_inventory.get(file_name, [])
        cargo_names = cargo_inventory.get(file_name, [])
        if sorted(source_names) != sorted(cargo_names):
            errors.append(
                f"{file_name}: source={source_names!r} cargo_list={cargo_names!r}"
            )
    return errors


def render_inventory_markdown(inventory: OrderedDict[str, list[str]]) -> str:
    total_files = len(inventory)
    contributing_files = count_files_with_goldens(inventory)
    total_tests = len(flatten_inventory(inventory))

    lines = [
        "# Generated Golden E2E Inventory",
        "",
        "This file is generated by `python3 scripts/golden_inventory.py --write --check-docs`.",
        "Do not hand-edit it.",
        "",
        "## Summary",
        "",
        f"- Golden test files: {total_files}",
        f"- Files contributing `golden_*` tests: {contributing_files}",
        f"- Total `golden_*` tests: {total_tests}",
        "",
        "## Per-File Inventory",
        "",
        "| File | `golden_*` tests |",
        "|------|------------------|",
    ]

    for file_name, tests in inventory.items():
        lines.append(f"| `{file_name}` | {len(tests)} |")

    for file_name, tests in inventory.items():
        lines.extend(
            [
                "",
                f"### `{file_name}`",
                "",
            ]
        )
        if not tests:
            lines.append("- No `golden_*` tests")
            continue
        for test_name in tests:
            lines.append(f"- `{test_name}`")

    lines.append("")
    return "\n".join(lines)


def validate_doc_test_references(
    inventory: OrderedDict[str, list[str]],
    docs: Iterable[pathlib.Path],
) -> list[str]:
    valid_tests = set(flatten_inventory(inventory))
    errors: list[str] = []
    for doc_path in docs:
        refs = DOC_TEST_REF_RE.findall(doc_path.read_text())
        missing = sorted({name for name in refs if name not in valid_tests})
        if missing:
            errors.append(f"{doc_path.relative_to(ROOT)}: missing references {missing}")
    return errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and validate the golden E2E inventory."
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the generated markdown inventory artifact.",
    )
    parser.add_argument(
        "--check-docs",
        action="store_true",
        help="Validate that golden docs only reference existing `golden_*` tests.",
    )
    parser.add_argument(
        "--skip-cargo-list",
        action="store_true",
        help="Skip the compiled `cargo test -p worldwake-ai -- --list` cross-check.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source_inventory = parse_source_inventory(TESTS_DIR)

    errors: list[str] = []
    if not args.skip_cargo_list:
        cargo_inventory = run_cargo_test_list(ROOT)
        errors.extend(compare_inventories(source_inventory, cargo_inventory))

    if args.check_docs:
        errors.extend(validate_doc_test_references(source_inventory, DOCS_TO_VALIDATE))

    markdown = render_inventory_markdown(source_inventory)
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(markdown)

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print(
        "golden inventory ok:"
        f" {len(source_inventory)} files,"
        f" {count_files_with_goldens(source_inventory)} contributing files,"
        f" {len(flatten_inventory(source_inventory))} tests"
    )
    if not args.write:
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
